### PR TITLE
Make 00E0 & 00EE as functions

### LINKED ISSUE #85: 00EE and 00E0 currently aren't considered as functions
They're evaluated directly, leading to an IndexOutOfRange Exception. 

The fix is easy to implement, we need to pass them an empty `()` argument (see `test` branch)

### PR DESCRIPTION
**Pull request by alarsyo**
Closes #85

Signed-off-by: Antoine Martin <antoine97.martin@gmail.com>

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ilnoumri** [comment]
There is still a problem with the main loop. Do you intend to fix it later with another pull request ?

**Comment by alarsyo** [comment]
Yup, not gonna throw all the code necessary to run the emulator along with these fixes 😛

**Comment by ilnoumri** [comment]
Ok then, seems good to me :) !

**Review by ilnoumri — APPROVED** [review]

**Comment by alarsyo** [comment]
Let's go

**Pull request merged**
